version: 1
update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: "monthly"
    ignored_updates:
      - match:
          dependency_name: "react-native"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
